export const DI_TYPE = {
  // Adapter Repository
  USER_REPOSITORY: 'USER_REPOSITORY',

  // UseCase
  REGISTER_USER_USE_CASE: 'REGISTER_USER_USER_CASE',
  SHOW_USER_USE_CASE: 'SHOW_USER_USE_CASE',

  // Adapter Handler
  DEBUG_PING_HANDLER: 'DEBUG_PING_HANDLER',
  DEBUG_REGISTER_USER_HANDLER: 'DEBUG_REGISTER_USER_HANDLER',
} as const
