@BASE_URL=http://localhost:3000

###

GET {{ BASE_URL }}/debug/ping

###

POST {{ BASE_URL }}/debug/users
Content-Type: application/json

{
    "id": "FOO_ID",
    "name": "Foo",
    "picture": "http://example.com/foo.jpg",
    "email": "foo@example.com"
}

###

POST {{ BASE_URL }}/oauth2/v2.1/verify
Content-Type: application/x-www-form-urlencoded

id_token=FOO_ID&client_id=1234567890

###

GET {{ BASE_URL }}/oauth2/v2.1/verify?access_token=FOO_ID
